# sculpt's configs are in the format `key = value`. They accept comments using the # character, and are resistant to trailing and leading spaces.
# note that logs regarding configs (eg. a malformed config or invalid key) don't respect the log level you set here - they are mostly logged, even at log_level = 0 (none).
# also, for code simplicity and performance, sculpt limits the max config line length to 256 characters (or, more specifically, SC_CONFIG_LINE_BUF, defined in sculpt.h.
# Longer lines (even lines with just comments) will throw an error.

log_level = 3 # 3 = debug
backlog_size = 23       
epoll_maxevents = 10
conn_recycling = false
conn_pool_size = 32
port = 8006
# address accepts an IP (eg. 0.0.0.0 or 127.0.0.1) or `localhost`
address = localhost
# times are in seconds
conn_max_age = 600
conn_timeout = 180
